server:
  port: 18088

spring:
  datasource:
    url: jdbc:mysql://localhost:3066/test?useSSL=false&useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 368000
    tomcat:
      max-active: 100
  messages:
    encoding: UTF-8

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.monitor.domain
  configuration:
    # 自动驼峰命名
    map-underscore-to-camel-case: false
